const RAIL_DESTINATIONS = [
  { nameCn: "沃尔西诺", nameEn: "Vorsino", stationCode: "183502", manzhouliPublic: { "20": 1767, "40": 4100 } },
  { nameCn: "谢利亚基诺", nameEn: "Selyatino", stationCode: "181102", manzhouliPublic: { "20": 1767, "40": 4100 } },
  { nameCn: "科利亚季奇", nameEn: "Kolyadichi", stationCode: "144809", manzhouliPublic: { "20": 2190, "40": 4500 } },
  { nameCn: "沙巴尼", nameEn: "Shabany", stationCode: "145201", manzhouliPublic: { "20": 2190, "40": 4500 } },
  { nameCn: "叶卡捷琳堡", nameEn: "Ekaterinburg-Tovarny", stationCode: "780302", manzhouliPublic: { "20": 1565, "40": 3300 } },
  { nameCn: "舒沙雷", nameEn: "Shushary-Logistika", stationCode: "033004", manzhouliPublic: { "20": 1830, "40": 4000 } },
  { nameCn: "克列希哈", nameEn: "Kleshchikha", stationCode: "850204", manzhouliPublic: { "20": 1209, "40": 2900 } },
];

const LEASE_PICKUPS = [
  { code: "SHANGHAI", nameCn: "上海", nameEn: "Shanghai", table: { "20": 400, "40": 2450 } },
  { code: "NINGBO", nameCn: "宁波", nameEn: "Ningbo", table: { "20": 300, "40": 2500 } },
  { code: "QINGDAO", nameCn: "青岛", nameEn: "Qingdao", table: { "20": 500, "40": 2100 } },
  { code: "XINGANG", nameCn: "天津新港", nameEn: "Xingang / Tianjin", table: { "20": 950, "40": 1850 } },
  { code: "DALIAN", nameCn: "大连", nameEn: "Dalian", table: { "20": 400, "40": 2000 } },
  { code: "GUANGZHOU", nameCn: "广州", nameEn: "Guangzhou", table: { "20": 550, "40": 2400 } },
  { code: "SHENZHEN", nameCn: "深圳", nameEn: "Shenzhen", table: { "20": 550, "40": 2500 } },
  { code: "XIAMEN", nameCn: "厦门", nameEn: "Xiamen", table: { "20": 1000, "40": 2200 } },
  { code: "ZHENGZHOU", nameCn: "郑州", nameEn: "Zhengzhou", table: { "20": 300, "40": 2200 } },
  { code: "XIAN", nameCn: "西安", nameEn: "Xi'an", table: { "20": 250, "40": 2100 } },
  { code: "CHENGDU", nameCn: "成都", nameEn: "Chengdu", table: { "20": 200, "40": 1800 } },
  { code: "CHONGQING", nameCn: "重庆", nameEn: "Chongqing", table: { "20": 200, "40": 2000 } },
  { code: "WUHAN", nameCn: "武汉", nameEn: "Wuhan", table: { "20": 300, "40": 2200 } },
  { code: "HARBIN", nameCn: "哈尔滨", nameEn: "Harbin", table: { "20": 1000, "40": 2300 } },
  { code: "SHENYANG", nameCn: "沈阳", nameEn: "Shenyang", table: { "20": 400, "40": 2200 } },
  { code: "SUIFENHE", nameCn: "绥芬河", nameEn: "Suifenhe", table: { "20": 1000, "40": 1450 } },
  { code: "CHANGSHA", nameCn: "长沙", nameEn: "Changsha", table: { "20": 200, "40": 2200 } },
  { code: "YIWU", nameCn: "义乌", nameEn: "Yiwu", table: { "20": 1000, "40": 2800 } },
  { code: "LIANYUNGANG", nameCn: "连云港", nameEn: "Lianyungang", table: { "20": 300, "40": 1400 } },
  { code: "SHANTOU", nameCn: "汕头", nameEn: "Shantou", table: { "20": null, "40": 2550 } },
  { code: "TAICANG", nameCn: "太仓", nameEn: "Taicang", table: { "20": 400, "40": 2300 } },
  { code: "ERLIAN", nameCn: "二连", nameEn: "Erlian", table: { "20": 1000, "40": 2550 } },
  { code: "CHANGCHUN", nameCn: "长春", nameEn: "Changchun", table: { "20": 1000, "40": 1200 } },
  { code: "HEFEI", nameCn: "合肥", nameEn: "Hefei", table: { "20": 1000, "40": 2300 } },
];

export function buildSeedRows() {
  const borders = [
    { code: "MANZHOULI", nameCn: "满洲里", nameEn: "Manzhouli", sortOrder: 10, enabled: true },
    { code: "ERLIAN", nameCn: "二连", nameEn: "Erlian", sortOrder: 20, enabled: true },
  ];

  const destinations = RAIL_DESTINATIONS.map((destination, index) => ({
    stationCode: destination.stationCode,
    nameCn: destination.nameCn,
    nameEn: destination.nameEn,
    sortOrder: (index + 1) * 10,
    enabled: true,
  }));

  const railPublicQuotes = RAIL_DESTINATIONS.flatMap((destination, destinationIndex) =>
    Object.entries(destination.manzhouliPublic).map(([containerSize, quoteUsd], index) => ({
      id: destinationIndex * 10 + index + 1,
      borderCode: "MANZHOULI",
      destinationStationCode: destination.stationCode,
      containerSize,
      quoteUsd,
      enabled: true,
    })),
  );

  const erLianFixed40 = [
    { stationCode: "181102", fixedUsd: 4300 },
    { stationCode: "183502", fixedUsd: 4300 },
    { stationCode: "144809", fixedUsd: 4330 },
  ];

  const railRules = [
    {
      id: 1,
      borderCode: "MANZHOULI",
      destinationStationCode: "",
      containerSize: "20",
      ownership: "*",
      ruleType: "adjustment",
      adjustmentUsd: 0,
      fixedUsd: null,
      ruleKey: "rule.rail.manzhouli20",
      priority: 10,
      note: "",
      enabled: true,
    },
    {
      id: 2,
      borderCode: "MANZHOULI",
      destinationStationCode: "",
      containerSize: "40",
      ownership: "SOC",
      ruleType: "adjustment",
      adjustmentUsd: -230,
      fixedUsd: null,
      ruleKey: "rule.rail.manzhouli40",
      priority: 10,
      note: "",
      enabled: true,
    },
    {
      id: 3,
      borderCode: "MANZHOULI",
      destinationStationCode: "",
      containerSize: "40",
      ownership: "COC",
      ruleType: "adjustment",
      adjustmentUsd: -200,
      fixedUsd: null,
      ruleKey: "rule.rail.manzhouli40",
      priority: 10,
      note: "",
      enabled: true,
    },
    {
      id: 4,
      borderCode: "ERLIAN",
      destinationStationCode: "",
      containerSize: "20",
      ownership: "*",
      ruleType: "unavailable",
      adjustmentUsd: null,
      fixedUsd: null,
      ruleKey: "error.rail.erlianNo20",
      priority: 5,
      note: "",
      enabled: true,
    },
    ...erLianFixed40.map((row, index) => ({
      id: index + 5,
      borderCode: "ERLIAN",
      destinationStationCode: row.stationCode,
      containerSize: "40",
      ownership: "*",
      ruleType: "fixed",
      adjustmentUsd: 0,
      fixedUsd: row.fixedUsd,
      ruleKey: "rule.rail.erlianFixed40",
      priority: 10,
      note: "",
      enabled: true,
    })),
  ];

  const leasePickups = LEASE_PICKUPS.map((pickup, index) => ({
    code: pickup.code,
    nameCn: pickup.nameCn,
    nameEn: pickup.nameEn,
    sortOrder: (index + 1) * 10,
    enabled: true,
  }));

  const leaseTablePrices = LEASE_PICKUPS.flatMap((pickup, pickupIndex) =>
    Object.entries(pickup.table)
      .filter(([, priceUsd]) => priceUsd !== null && priceUsd !== undefined)
      .map(([containerSize, priceUsd], index) => ({
        id: pickupIndex * 10 + index + 1,
        pickupCode: pickup.code,
        containerSize,
        priceUsd,
        enabled: true,
      })),
  );

  const leaseRules = [
    {
      id: 1,
      borderCode: "MANZHOULI",
      pickupCode: "",
      containerSize: "20",
      ruleType: "adjustment",
      adjustmentUsd: -100,
      fixedUsd: null,
      ruleKey: "rule.lease.manzhouli20",
      priority: 10,
      note: "",
      enabled: true,
    },
    {
      id: 2,
      borderCode: "MANZHOULI",
      pickupCode: "TAICANG",
      containerSize: "40",
      ruleType: "fixed",
      adjustmentUsd: null,
      fixedUsd: 1900,
      ruleKey: "rule.lease.manzhouli40Taicang",
      priority: 20,
      note: "",
      enabled: true,
    },
    {
      id: 3,
      borderCode: "MANZHOULI",
      pickupCode: "XINGANG",
      containerSize: "40",
      ruleType: "adjustment",
      adjustmentUsd: -150,
      fixedUsd: null,
      ruleKey: "rule.lease.manzhouli40Other",
      priority: 15,
      note: "",
      enabled: true,
    },
    {
      id: 4,
      borderCode: "MANZHOULI",
      pickupCode: "",
      containerSize: "40",
      ruleType: "adjustment",
      adjustmentUsd: -350,
      fixedUsd: null,
      ruleKey: "rule.lease.manzhouli40Other",
      priority: 10,
      note: "",
      enabled: true,
    },
    {
      id: 5,
      borderCode: "ERLIAN",
      pickupCode: "",
      containerSize: "20",
      ruleType: "unavailable",
      adjustmentUsd: null,
      fixedUsd: null,
      ruleKey: "error.lease.erlianNo20",
      priority: 10,
      note: "",
      enabled: true,
    },
    {
      id: 6,
      borderCode: "ERLIAN",
      pickupCode: "TAICANG",
      containerSize: "40",
      ruleType: "fixed",
      adjustmentUsd: null,
      fixedUsd: 1930,
      ruleKey: "rule.lease.erlian40Taicang",
      priority: 20,
      note: "",
      enabled: true,
    },
    {
      id: 7,
      borderCode: "ERLIAN",
      pickupCode: "",
      containerSize: "40",
      ruleType: "adjustment",
      adjustmentUsd: -150,
      fixedUsd: null,
      ruleKey: "rule.lease.erlian40Other",
      priority: 10,
      note: "",
      enabled: true,
    },
  ];

  return {
    borders,
    destinations,
    railPublicQuotes,
    railRules,
    leasePickups,
    leaseTablePrices,
    leaseRules,
  };
}
