export const ADMIN_RESOURCES = [
  {
    key: "borders",
    labelKey: "admin.resources.borders",
    idField: "code",
    table: "rail_cost_borders",
    fields: [
      { key: "code", type: "text", required: true },
      { key: "nameCn", type: "text", required: true },
      { key: "nameEn", type: "text", required: true },
      { key: "sortOrder", type: "number", required: true },
      { key: "enabled", type: "boolean", required: true },
    ],
  },
  {
    key: "destinations",
    labelKey: "admin.resources.destinations",
    idField: "stationCode",
    table: "rail_cost_destinations",
    fields: [
      { key: "stationCode", type: "text", required: true },
      { key: "nameCn", type: "text", required: true },
      { key: "nameEn", type: "text", required: true },
      { key: "sortOrder", type: "number", required: true },
      { key: "enabled", type: "boolean", required: true },
    ],
  },
  {
    key: "rail-public-quotes",
    labelKey: "admin.resources.railPublicQuotes",
    idField: "id",
    table: "rail_cost_rail_public_quotes",
    fields: [
      { key: "id", type: "number", readonly: true },
      { key: "borderCode", type: "text", required: true, reference: { collection: "borders", valueKey: "code" } },
      { key: "destinationStationCode", type: "text", required: true, reference: { collection: "destinations", valueKey: "stationCode" } },
      { key: "containerSize", type: "text", required: true },
      { key: "quoteUsd", type: "number", required: true },
      { key: "enabled", type: "boolean", required: true },
    ],
  },
  {
    key: "rail-rules",
    labelKey: "admin.resources.railRules",
    idField: "id",
    table: "rail_cost_rail_rules",
    fields: [
      { key: "id", type: "number", readonly: true },
      { key: "borderCode", type: "text", required: true, reference: { collection: "borders", valueKey: "code" } },
      { key: "destinationStationCode", type: "text", reference: { collection: "destinations", valueKey: "stationCode" } },
      { key: "containerSize", type: "text", required: true },
      { key: "ownership", type: "text", required: true },
      { key: "ruleType", type: "text", required: true },
      { key: "adjustmentUsd", type: "number" },
      { key: "fixedUsd", type: "number" },
      { key: "ruleKey", type: "text" },
      { key: "priority", type: "number", required: true },
      { key: "note", type: "text" },
      { key: "enabled", type: "boolean", required: true },
    ],
  },
  {
    key: "lease-pickups",
    labelKey: "admin.resources.leasePickups",
    idField: "code",
    table: "rail_cost_lease_pickups",
    fields: [
      { key: "code", type: "text", required: true },
      { key: "nameCn", type: "text", required: true },
      { key: "nameEn", type: "text", required: true },
      { key: "sortOrder", type: "number", required: true },
      { key: "enabled", type: "boolean", required: true },
    ],
  },
  {
    key: "lease-table-prices",
    labelKey: "admin.resources.leaseTablePrices",
    idField: "id",
    table: "rail_cost_lease_table_prices",
    fields: [
      { key: "id", type: "number", readonly: true },
      { key: "pickupCode", type: "text", required: true, reference: { collection: "leasePickups", valueKey: "code" } },
      { key: "containerSize", type: "text", required: true },
      { key: "priceUsd", type: "number", required: true },
      { key: "enabled", type: "boolean", required: true },
    ],
  },
  {
    key: "lease-rules",
    labelKey: "admin.resources.leaseRules",
    idField: "id",
    table: "rail_cost_lease_rules",
    fields: [
      { key: "id", type: "number", readonly: true },
      { key: "borderCode", type: "text", required: true, reference: { collection: "borders", valueKey: "code" } },
      { key: "pickupCode", type: "text", reference: { collection: "leasePickups", valueKey: "code" } },
      { key: "containerSize", type: "text", required: true },
      { key: "ruleType", type: "text", required: true },
      { key: "adjustmentUsd", type: "number" },
      { key: "fixedUsd", type: "number" },
      { key: "ruleKey", type: "text" },
      { key: "priority", type: "number", required: true },
      { key: "note", type: "text" },
      { key: "enabled", type: "boolean", required: true },
    ],
  },
];

export function getAdminResource(key) {
  return ADMIN_RESOURCES.find((resource) => resource.key === key);
}
